name: Deploy to GitHub Pages

on:
  push:
    branches: [ main ]      # ← メインブランチ名

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: pages
  cancel-in-progress: true

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # 1️⃣ ソース取得
      - uses: actions/checkout@v4

      # 2️⃣ Node + npm キャッシュ
      - uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: npm
          # cache-dependency-path: nuxt-app/package-lock.json

      # 3️⃣ 依存インストール
      - name: Install dependencies
        run: npm ci --legacy-peer-deps
        working-directory: nuxt-app

      # 4️⃣ 静的サイト生成 (.output/public)
      - name: Generate site
        run: npm run generate
        working-directory: nuxt-app

      # 5️⃣ 成果物を Pages 用 artifact としてアップロード (v3 = artifact v4 対応)
      - name: Upload Pages artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: nuxt-app/.output/public     # 出力先
          name: github-pages               # 既定名

  deploy:
    needs: build
    runs-on: ubuntu-latest

    steps:
      # Pages を有効化（推奨）
      - uses: actions/configure-pages@v5   # :contentReference[oaicite:1]{index=1}

      # アップロード済み artifact をデプロイ (v4 = artifact v4 対応)
      - id: deploy
        uses: actions/deploy-pages@v4
